import "dart:async";
import "dart:collection";

import "package:analyzer/dart/element/element.dart";
import "package:build/build.dart";
import "package:code_builder/code_builder.dart";
import "package:dart_style/dart_style.dart";
import "package:glob/glob.dart";

import "package:gql_code_builder/serializer.dart";
import "package:path/path.dart" as p;

import "./allocators/pick_allocator.dart";
import "./config.dart";

/// Aggregates all `built_value` `Serializers` generated by any of the gql builders.
class SerializerBuilder implements Builder {
  final AssetId schemaId;
  final Set<Reference> customSerializers;
  final Map<String, Reference> typeOverrides;

  SerializerBuilder(
    this.schemaId,
    this.customSerializers,
    this.typeOverrides,
  );

  static final _formatter =
      DartFormatter(languageVersion: DartFormatter.latestLanguageVersion);
  static final _generatedFiles = Glob("lib/**.gql.dart");

  // create a path for the serializers output in same directory as schema
  List<String> get pathSegments =>
      outputAssetId(schemaId, serializerExtension).pathSegments
        ..removeLast()
        ..add("serializers.gql.dart");

  @override
  Map<String, List<String>> get buildExtensions => {
        // buildExtensions already include the 'lib' path segment, so we must remove it here
        r"$lib$": [p.joinAll(pathSegments.skip(1))],
      };

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    /// BuiltValue classes with serializers. These will be added automatically
    /// using `@SerializersFor`.
    final builtClasses =
        SplayTreeSet<ClassElement>((a, b) => a.name.compareTo(b.name));

    /// Non BuiltValue classes with serializers (i.e. inline fragment classes).
    /// These need to be added manually since `@SerializersFor` only recognizes
    /// BuiltValue classes.
    final nonBuiltClasses =
        SplayTreeSet<ClassElement>((a, b) => a.name.compareTo(b.name));

    final hasSerializer = (ClassElement c) => c.fields.any((field) =>
        field.isStatic &&
        field.name == "serializer" &&
        field.type.element?.name == "Serializer" &&
        field.type.element?.source?.uri.toString() ==
            "package:built_value/serializer.dart");

    final isBuiltValue = (ClassElement c) => c.allSupertypes.any((interface) =>
        (interface.element.name == "Built" ||
            interface.element.name == "EnumClass") &&
        interface.element.source.uri.toString() ==
            "package:built_value/built_value.dart");

    await for (final input in buildStep.findAssets(_generatedFiles)) {
      final lib = await buildStep.resolver.libraryFor(input);
      lib.units
          .expand((cu) => cu.classes)
          .where((c) => hasSerializer(c) && isBuiltValue(c))
          .forEach(builtClasses.add);

      lib.units
          .expand((cu) => cu.classes)
          .where(
            (c) => hasSerializer(c) && !isBuiltValue(c),
          )
          .forEach(nonBuiltClasses.add);
    }

    // Collect URIs for non-built classes to ensure they can be imported if needed
    final nonBuiltClassUris = nonBuiltClasses
        .map((c) => c.source.uri.toString())
        .whereType<String>()
        .toSet();

    // Initialize allocator *after* collecting all necessary URIs
    final allocator = PickAllocator(
      doNotPick: ["package:built_value/serializer.dart"],
      // Convert the set of includes to a list
      include: {
        // Ensure built_collection is included for ListBuilder serializers
        "package:built_collection/built_collection.dart",
        // Include user-defined type overrides
        ...typeOverrides.values.map((ref) => ref.url).whereType<String>(),
        // Include sources of non-built classes used in built_value classes
        ...nonBuiltClassUris,
      }.toList(), // Convert the Set to a List
    );

    final Set<Expression> additionalSerializers = {
      // GraphQL Operation serializer
      refer(
        "OperationSerializer",
        "package:gql_code_builder_serializers/gql_code_builder_serializers.dart",
      ).call([]),
      // User-defined custom serializers
      ...customSerializers.map((ref) => ref.call([])),
      // Serializers from data classes that aren't caught by `@SerializersFor`
      ...nonBuiltClasses.map<Expression>(
        (c) => refer(c.name, c.source.uri.toString()).property("serializer"),
      ),
    };

    final library = buildSerializerLibrary(
      builtClasses,
      "serializers.gql.g.dart",
      additionalSerializers,
    );

    final _emitter = DartEmitter(
      allocator: allocator,
      orderDirectives: true,
      useNullSafetySyntax: true,
    );

    final output = AssetId(
      buildStep.inputId.package,
      p.joinAll(pathSegments),
    );

    return buildStep.writeAsString(
      output,
      _formatter.format("${library.accept(_emitter)}"),
    );
  }
}
