// Mocks generated by Mockito 5.0.0-nullsafety.7 from annotations
// in gql_http_link/test/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;
import 'dart:convert' as _i9;
import 'dart:typed_data' as _i3;

import 'package:gql_exec/src/error.dart' as _i6;
import 'package:gql_exec/src/request.dart' as _i12;
import 'package:gql_exec/src/response.dart' as _i5;
import 'package:gql_link/src/request_serializer.dart' as _i11;
import 'package:gql_link/src/response_parser.dart' as _i13;
import 'package:http/src/base_request.dart' as _i10;
import 'package:http/src/client.dart' as _i7;
import 'package:http/src/response.dart' as _i2;
import 'package:http/src/streamed_response.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeResponse extends _i1.Fake implements _i2.Response {}

class _FakeUint8List extends _i1.Fake implements _i3.Uint8List {}

class _FakeStreamedResponse extends _i1.Fake implements _i4.StreamedResponse {}

class _FakeResponse extends _i1.Fake implements _i5.Response {}

class _FakeGraphQLError extends _i1.Fake implements _i6.GraphQLError {}

class _FakeErrorLocation extends _i1.Fake implements _i6.ErrorLocation {}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i7.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future.value(_FakeResponse()))
          as _i8.Future<_i2.Response>);
  @override
  _i8.Future<_i2.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future.value(_FakeResponse()))
          as _i8.Future<_i2.Response>);
  @override
  _i8.Future<_i2.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future.value(_FakeResponse()))
          as _i8.Future<_i2.Response>);
  @override
  _i8.Future<_i2.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future.value(_FakeResponse()))
          as _i8.Future<_i2.Response>);
  @override
  _i8.Future<_i2.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future.value(_FakeResponse()))
          as _i8.Future<_i2.Response>);
  @override
  _i8.Future<_i2.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future.value(_FakeResponse()))
          as _i8.Future<_i2.Response>);
  @override
  _i8.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future.value('')) as _i8.Future<String>);
  @override
  _i8.Future<_i3.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future.value(_FakeUint8List()))
          as _i8.Future<_i3.Uint8List>);
  @override
  _i8.Future<_i4.StreamedResponse> send(_i10.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue: Future.value(_FakeStreamedResponse()))
          as _i8.Future<_i4.StreamedResponse>);
}

/// A class which mocks [RequestSerializer].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestSerializer extends _i1.Mock implements _i11.RequestSerializer {
  MockRequestSerializer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> serializeRequest(_i12.Request? request) =>
      (super.noSuchMethod(Invocation.method(#serializeRequest, [request]),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}

/// A class which mocks [ResponseParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponseParser extends _i1.Mock implements _i13.ResponseParser {
  MockResponseParser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Response parseResponse(Map<String, dynamic>? body) =>
      (super.noSuchMethod(Invocation.method(#parseResponse, [body]),
          returnValue: _FakeResponse()) as _i5.Response);
  @override
  _i6.GraphQLError parseError(Map<String, dynamic>? error) =>
      (super.noSuchMethod(Invocation.method(#parseError, [error]),
          returnValue: _FakeGraphQLError()) as _i6.GraphQLError);
  @override
  _i6.ErrorLocation parseLocation(Map<String, dynamic>? location) =>
      (super.noSuchMethod(Invocation.method(#parseLocation, [location]),
          returnValue: _FakeErrorLocation()) as _i6.ErrorLocation);
}
