name: cats
description: A starting point for Dart libraries or applications.
repository: https://github.com/gql-dart/gql
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  test: ^1.16.0
dev_dependencies: 
  pedantic: ^1.10.0
  yaml: ^3.0.0
