name: normalize
version: 0.0.1
description: Normalization and denormalization of GraphQL responses in Dart
author: Sat Mandir Khalsa
homepage: https://github.com/smkhalsa/normalize
repository: https://github.com/smkhalsa/normalize

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  gql: ^0.11.1

dev_dependencies:
  test: ^1.9.4
  gql_pedantic: ^1.0.0
