name: normalize
author: Sat Mandir Khalsa
version: 0.0.1
homepage: https://github.com/gql-dart/gql/tree/master/normalize
description: Normalization and denormalization of GraphQL responses in Dart
repository: https://github.com/gql-dart/gql/tree/master/normalize
environment: 
  sdk: '>=2.2.2 <3.0.0'
dependencies: 
  gql: ^0.11.1
dev_dependencies: 
  test: ^1.9.4
  gql_pedantic: ^1.0.0
