name: gql_example_build
environment: 
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies: 
  build_runner: ^2.0.0
  gql_build: ^0.7.0
  gql_pedantic: ^1.0.2
  test: ^1.0.0
dependency_overrides: 
  gql_pedantic: 
    path: ../../gql_pedantic
  gql: 
    path: ../../gql
  gql_exec: 
    path: ../../links/gql_exec
  gql_link: 
    path: ../../links/gql_link
  gql_websocket_link: 
    path: ../../links/gql_websocket_link
  gql_transform_link: 
    path: ../../links/gql_transform_link
  gql_http_link: 
    path: ../../links/gql_http_link
  gql_error_link: 
    path: ../../links/gql_error_link
  gql_code_builder: 
    path: ../../codegen/gql_code_builder
  gql_build: 
    path: ../../codegen/gql_build
  gql_example_http_auth_link: 
    path: ../gql_example_http_auth_link
  gql_dio_link: 
    path: ../../links/gql_dio_link
  gql_example_dio_link: 
    path: ../gql_example_dio_link
  gql_example_cli_github: 
    path: ../gql_example_cli_github
  gql_example_cli: 
    path: ../gql_example_cli
  gql_dedupe_link: 
    path: ../../links/gql_dedupe_link
  end_to_end_test: 
    path: ../../codegen/end_to_end_test
