query GetBooks {
  books {
    ...BookFragment
  }
} 

fragment BookFragment on Book {
  author {
    ...AuthorFragment
  }
  title
  ... on Textbook {
      courses
  }
  ... on ColoringBook {
      colors
  }
}

fragment AuthorFragment on Author {
  displayName
  ... on Person {
    ...AuthorPersonFragment
  }
  ... on Company {
    ...AuthorCompanyFragment
  }
  ... on Group {
    members {
      ...AuthorGroupFragment
    }
  }
}

fragment AuthorPersonFragment on Person {
  firstName
  lastName
}

fragment AuthorCompanyFragment on Company {
  name
}

fragment AuthorGroupFragment on Author {
  displayName
  ... on Person {
    ...AuthorPersonFragment
  }
  ... on Company {
    ...AuthorCompanyFragment
  }
}

