builders:
  ast_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["astBuilder"]
    build_extensions: {".graphql": [".ast.gql.dart"]}
    auto_apply: none
    build_to: source
  op_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["opBuilder"]
    build_extensions: {".graphql": [".op.gql.dart"]}
    auto_apply: none
    build_to: source
  data_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["dataBuilder"]
    build_extensions: {".graphql": [".data.gql.dart"]}
    auto_apply: none
    build_to: source
  req_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["reqBuilder"]
    build_extensions: {".graphql": [".req.gql.dart"]}
    auto_apply: none
    build_to: source
  enum_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["enumBuilder"]
    build_extensions: {".graphql": [".enum.gql.dart"]}
    auto_apply: none
    build_to: source
  scalar_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["scalarBuilder"]
    build_extensions: {".graphql": [".scalar.gql.dart"]}
    auto_apply: none
    build_to: source
  input_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["inputBuilder"]
    build_extensions: {".graphql": [".input.gql.dart"]}
    auto_apply: none
    build_to: source
  schema_builder:
    import: "package:gql_build/gql_build.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: {".graphql": [".schema.gql.dart"]}
    auto_apply: none
    build_to: source
