targets:
  $default:
    builders:
      gql_build|ast_builder:
        enabled: true
        options:
          format:
            page_width: 80
            language_version: '3.6.0'
      gql_build|req_builder:
        enabled: true
        options:
          schema: gql_example_cli_github|lib/schema.graphql
          format:
            page_width: 80
            language_version: '3.6.0'
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: gql_example_cli_github|lib/schema.graphql
          format:
            page_width: 80
            language_version: '3.6.0'
      gql_build|schema_builder:
        enabled: true
        options:
          format:
            page_width: 80
            language_version: '3.6.0'
      gql_build|data_builder:
        enabled: true
        options:
          schema: gql_example_cli_github|lib/schema.graphql
          format:
            page_width: 80
            language_version: '3.6.0'
      gql_build|var_builder:
        enabled: true
        options:
          schema: gql_example_cli_github|lib/schema.graphql
          format:
            page_width: 80
            language_version: '3.6.0'
